# Generated by Django 5.0.7 on 2024-07-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('datetime_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='data/hora')),
                ('description', models.TextField(verbose_name='descrição')),
                ('services', models.CharField(choices=[('Corte', 'Corte: R$ 50 - R$ 200'), ('Coloração', 'Tintura Completa: R$ 100 - R$ 400'), ('Mexas/Reflexos', 'Mechas/Reflexos: R$ 150 - R$ 600'), ('Hidratação', 'Hidratação: R$ 50 - R$ 150'), ('Botox', 'Botox Capilar: R$ 200 - R$ 500'), ('Escova', 'Escova Simples: R$ 30 - R$ 80'), ('Progressiva', 'Escova Progressiva: R$ 200 - R$ 800')], max_length=50, verbose_name='serviço')),
                ('done', models.CharField(choices=[('doing', 'doing'), ('done', 'done')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
